apiVersion: v1
kind: Service
metadata:
  name: msgsend-service
spec:
  selector:
    app: msgsend
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodPort: 31003
  type: LoadBalancer  # Ou NodePort
